// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkwwgKzhNJop9WjczwDsXQ8JjBo8-ceN8',
    appId: '1:409251052150:web:c435e06204e9f31d0c3d57',
    messagingSenderId: '409251052150',
    projectId: 'projex',
    authDomain: 'projex-6fd03.firebaseapp.com',
    storageBucket: 'projex.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA0I29KaU3QCW5VQIhkb-eOWjy9j0W9II',
    appId: '1:409251052150:android:e6779102b68fb4ca0c3d57',
    messagingSenderId: '409251052150',
    projectId: 'projex',
    storageBucket: 'projex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgBFfT6IhhesaIgnMDc1_B5OpwRjsik18',
    appId: '1:409251052150:ios:2480f2345d7868480c3d57',
    messagingSenderId: '409251052150',
    projectId: 'projex',
    storageBucket: 'projex.appspot.com',
    iosBundleId: 'com.example.cyclops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgBFfT6IhhesaIgnMDc1_B5OpwRjsik18',
    appId: '1:409251052150:ios:ce71e3e4ac21bea80c3d57',
    messagingSenderId: '409251052150',
    projectId: 'projex',
    storageBucket: 'projex.appspot.com',
    iosBundleId: 'com.example.cyclops.RunnerTests',
  );
}
